version: 2
mergeable:  
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: label
        must_exclude:
          regex: 'wip'
          message: 'PRs with wip label cannot be merged'
      - do: milestone
        no_empty:
          enabled: true
          message: 'PRs must be associated to a milestone'
      - do: project
        no_empty:
          enabled: true
          message: 'PRs must be associated to a project'          
    fail:
      - do: results_as_review
    pass:
      - do: results_as_review
