version: 2
mergeable:  
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: label
        must_exclude:
          regex: 'wip'
    fail:
      - do: comment
        payload:
          body: >
            PRs with a wip label cannot be merged
