name: Check Issues

on: issues

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  check-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check Issues
        uses: mattlock83/mergeable-github-action-example@v0.3
        with:
          config_file: 'issue-rules.yml'
